connection: &connection
  adapter: postgresql
  encoding: unicode
  host:     localhost
  pool: 5
  username: username
  password: password

development:
  <<: *connection
  database: workshops_development
  username: username
  password: password


test: &test
  <<: *connection
  database: workshops_test
  username: username
  password: password

